// <auto-generated />
namespace ConestogaHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kunal_21_09_add_tbl_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kunal_21_09_add_tbl_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201909211518061_kunal_21_09_add_tbl_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
