// <auto-generated />
namespace ConestogaHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kunal_04_11_2019_add_tbl_floor_management : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kunal_04_11_2019_add_tbl_floor_management));
        
        string IMigrationMetadata.Id
        {
            get { return "201911041416016_kunal_04_11_2019_add_tbl_floor_management"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
