// <auto-generated />
namespace ConestogaHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kunal_28_09_modify_tbl_doctor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kunal_28_09_modify_tbl_doctor));
        
        string IMigrationMetadata.Id
        {
            get { return "201909282030402_kunal_28_09_modify_tbl_doctor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
