// <auto-generated />
namespace ConestogaHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kunal08_10_2019_add_tbl_appointment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kunal08_10_2019_add_tbl_appointment));
        
        string IMigrationMetadata.Id
        {
            get { return "201910081337355_kunal-08_10_2019_add_tbl_appointment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
