// <auto-generated />
namespace ConestogaHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kunal_15_10_2019_modify_token : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kunal_15_10_2019_modify_token));
        
        string IMigrationMetadata.Id
        {
            get { return "201910151805527_kunal_15_10_2019_modify_token"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
